parameters:
#    gds_photo.example.class: GDS\PhotoBundle\Example

services:
#    gds_photo.example:
#        class: %gds_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
