GDS_order_listeResto:
    pattern:  /
    defaults: { _controller: GDSOrderBundle:Order:index }
    
GDS_order_menu:
    pattern: /{resto}
    defaults: { _controller: GDSOrderBundle:Order:menu }
    requirements:
        resto: mcdo|subway|grec|nooi|thevenin|bdoree|asie|wokbar

GDS_order_recap:
    pattern: /recap
    defaults: { _controller: GDSOrderBundle:Order:recap }

GDS_order_confirm:
    pattern: /confirm
    defaults: { _controller: GDSOrderBundle:Order:confirm }