parameters:
#    gds_home.example.class: GDS\HomeBundle\Example

services:
#    gds_home.example:
#        class: %gds_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
